### ISSUE TITLE
使用心率传感器过程中数据出现乱码

### ISSUE THREAD

**Issue by nickzhums** [DFRobot/DFRobot_Heartrate#2]
Hi DF Robot 心率传感器创作者，
打扰了，我在使用该心率传感器过程出现了数据乱码的问题，即通过代码打印在Serial Monitor上的数据不是应该有的心率数字，而是一串串的乱码。（具体现象可以见视频和图片），由于我尝试各种方法无法解决所以只能来发信求助

我的线路连接和代码都是从官方文档上直接复制过来的，具体是这个网站：https://wiki.dfrobot.com.cn/_SKU_SEN0203_%E5%BF%83%E7%8E%87%E4%BC%A0%E6%84%9F%E5%99%A8heart_rate_sensor#target_3

没有对样例代码进行过任何改动，因此应该不是代码的问题，线路连接也是比较简单的，但我使用了一个公对公的连接线，理论上应该这个也不会造成问题，因此我目前想不到哪里还能出错，所以发邮件来求助，十分感谢。希望能得到一些帮助，谢谢！
![heartrate1](https://user-images.githubusercontent.com/56864335/215272513-712f48d3-7177-4721-a147-535ba9870ab0.jpg)
![heartrate2](https://user-images.githubusercontent.com/56864335/215272517-9306f1f6-f5d2-424e-86dd-5373a552d9b8.jpg)

https://user-images.githubusercontent.com/56864335/215272786-f05b0322-7df8-411d-ac08-242e59aeff50.mp4

**Comment by nickzhums** [comment]
@qsjhyy

**Comment by qsjhyy** [comment]
@nickzhums 
![image](https://user-images.githubusercontent.com/78136558/215298800-22940ac8-cd51-4d6a-81a7-3ce81c48af33.png)

**Comment by nickzhums** [comment]
谢谢，问题解决了
